// 保留原有枚举定义，供外部使用
typedef enum {
    Data_Target = 0,
    Data_Position,
    Data_Velocity,
    Data_Current,
    Data_Motor_Tempe,
    Data_Driver_Tempe,
    Data_CMD_Start,
    Data_CMD_Reset,
    Data_CMD_Set_PID,
    Data_CMD_Set_Period,
    Data_CMD_Stop,
    Data_CMD_Jog,
    Data_CMD_Forw,
    Data_CMD_Reve,
    Data_CMD_Text,
    Data_Ctrl_Pos,
    Data_Ctrl_Vel,
    Data_Ctrl_Tor,
    Data_Ctrl_Open_Pos,
    Data_Ctrl_Open_Vel,
    Data_Ctrl_Sensorless_Vel,
    Data_Ctrl_Stop_Quick,
    Data_Res_Start,
    Data_Res_Stop,
    Data_Channel1,
    Data_Channel2,
    Data_Channel3,
    Data_Channel4,
    Data_Channel5,
    Data_Unknown,
} DataTypes;